### Root Certificates - Get all
GET http://localhost:5202/api/RootCertificates
Accept: application/json

###

### Root Certificates - Get by id
GET http://localhost:5202/api/RootCertificates/14193eb9-2e68-4282-b1cd-fccacfe46663
Accept: application/json

###

### Root Certificates - Create
POST http://localhost:5202/api/RootCertificates
Content-Type: application/json

{
  "name": "Test Root CA",
  "certificateData": "TEST_ROOT_CERT"
}

###

### Root Certificates - Update
PUT http://localhost:5202/api/RootCertificates/14193eb9-2e68-4282-b1cd-fccacfe46663
Content-Type: application/json

{
  "name": "Updated Root CA",
  "certificateData": "UPDATED_ROOT_CERT"
}

###

### Root Certificates - Delete
DELETE http://localhost:5202/api/RootCertificates/14193eb9-2e68-4282-b1cd-fccacfe46663

###

### User Certificates - Get all
GET http://localhost:5202/api/UserCertificates
Accept: application/json

###

### User Certificates - Get by id
GET http://localhost:5202/api/UserCertificates/c3ee10f0-95ae-4410-8e42-2092beeca2de
Accept: application/json

###

### User Certificates - Create
POST http://localhost:5202/api/UserCertificates
Content-Type: application/json

{
  "username": "u4fps0",
  "certificateData": "TEST_USER_CERT",
  "rootCertificateId": "42593ba2-52d4-403d-bd0f-5407fea35ff9"
}

###

### User Certificates - Update
PUT http://localhost:5202/api/UserCertificates/c3ee10f0-95ae-4410-8e42-2092beeca2de
Content-Type: application/json

{
  "username": "updated-grandma-user",
  "certificateData": "UPDATED_USER_CERT",
  "rootCertificateId": "42593ba2-52d4-403d-bd0f-5407fea35ff9"
}

###

### User Certificates - Delete
DELETE http://localhost:5202/api/UserCertificates/c3ee10f0-95ae-4410-8e42-2092beeca2de