apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "measurement-results-system.fullname" . }}-frontend
  labels:
    {{- include "measurement-results-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "measurement-results-system.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "measurement-results-system.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image | default (printf "%s/%s:%s" .Values.global.imageRegistry "alkfej_beadando_u4fps0/frontend" .Values.global.imageTag) }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "measurement-results-system.fullname" . }}-frontend
  labels:
    {{- include "measurement-results-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "measurement-results-system.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80