name: Build and Push Docker Images

on:
  push:
    branches:
      - main

##Trigger the workflow on pull requests to the main branch
  pull_request:
    branches:
      - main
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/kochard/alkfej_beadando_u4fps0/backend:latest ./backend-api/CertificateStore.Api
          docker push ghcr.io/kochard/alkfej_beadando_u4fps0/backend:latest
      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/kochard/alkfej_beadando_u4fps0/frontend:latest ./frontend/certificate-store-frontend
          docker push ghcr.io/kochard/alkfej_beadando_u4fps0/frontend:latest
#